[package]
name = "txtx-ext-bitcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
# strum = "0.25.0"
# strum_macros = "0.25.3"
txtx-ext-kit = { path = "../txtx-ext-kit" }

[features]
wasm = ["txtx-ext-kit/wasm"]

[lib]
crate-type = ["lib", "cdylib"] 