[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/txtx/txtx"
keywords = ["txtx", "smart-contracts", "devops", "secops", "blockchains"]
categories = ["cryptography"]

[workspace]
members = [
    "crates/txtx-cli",
    "crates/txtx-core",
    "crates/txtx-addon-kit",
    "crates/txtx-lsp",
    "addons/bitcoin",
    "addons/evm",
    "addons/stacks",
    "addons/telegram"
]
default-members = ["crates/txtx-cli"]
resolver = "2"

[workspace.dependencies]
txtx-core = { path = "crates/txtx-core" }
txtx-gql = { path = "crates/txtx-gql" }
txtx-addon-kit = { path = "crates/txtx-addon-kit" }
txtx-addon-network-evm = { path = "addons/evm" }
txtx-addon-network-bitcoin = { path = "addons/bitcoin" }
txtx-addon-network-stacks = { path = "addons/stacks" }
txtx-addon-telegram = { path = "addons/telegram" }
