[workspace]
members = [
    "components/txtx-cli",
    "components/txtx-core",
    "components/txtx-ext-kit",
    "components/txtx-ext-bitcoin"
]
default-members = ["components/txtx-cli"]
resolver = "2"
