[workspace]
members = [
    "components/txtx-cli",
    "components/txtx-core",
    "components/txtx-addon-kit",
    "components/txtx-lsp",
    "addons/bitcoin",
    "addons/evm",
    "addons/stacks",
    "addons/telegram"
]
default-members = ["components/txtx-cli"]
resolver = "2"
