[alias]
txtx-install = "install --path crates/txtx-cli --features supervisor_ui --features ovm --locked --force"
build-cli = "build --package txtx-cli --no-default-features --features cli"
build-cli-release = "build --package txtx-cli --no-default-features --features cli --release"
test-cli = "test --package txtx-cli --no-default-features --features cli"
test-cli-doctor = "test --package txtx-cli --no-default-features --features cli doctor"
# QA improvement aliases
# Note: Use test-cli for testing without supervisor UI build issues
# The supervisor UI is an optional dependency of txtx-cli, so we need to disable default features

[build]
rustflags = ["--cfg", "tokio_unstable"]



